/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Hospitalizacion;
import Modelo.Persona;
import static Vista.frmHospitalizacion.ch;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Personal
 */
public class frmListaHospitalización extends javax.swing.JDialog {

    ArrayList<Hospitalizacion> listaHosp;
    Hospitalizacion eleccion;
    ArrayList<Persona> listPersonas;

    /**
     * Creates new form frmListaHospitalización
     */
    public frmListaHospitalización(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        listaHosp = ch.getListaConsulta();
        llenarTabla(listaHosp);
    }

    public void llenarTabla(ArrayList<Hospitalizacion> lista) {

        DefaultTableModel tabla = new DefaultTableModel(new String[]{"MASCOTA", "SEXO", "CEDULA", "DUEÑO", "VETERINARIO", "FECHA DE INGRESO", "ESTADO"}, lista.size());
        jTableHospi.setModel(tabla);
        TableModel datosTabla = jTableHospi.getModel();

        for (int i = 0; i < lista.size(); i++) {
            datosTabla.setValueAt(lista.get(i).getMascota().getNombre(), i, 0);
            datosTabla.setValueAt(lista.get(i).getMascota().getSexo(), i, 1);
            datosTabla.setValueAt(lista.get(i).getMascota().getPersona().getCedula(), i, 2);
            String nombres = lista.get(i).getMascota().getPersona().getNombre() + " " + lista.get(i).getMascota().getPersona().getApellido();
            datosTabla.setValueAt(nombres, i, 3);
            datosTabla.setValueAt(lista.get(i).getVereterinario(), i, 4);
            datosTabla.setValueAt(lista.get(i).getIngreso(), i, 5);
            datosTabla.setValueAt(lista.get(i).getEstado(), i, 6);
        }
    }

    private static boolean esNumerico(String cadena) {
        try {
            Integer.parseInt(cadena);
            return true;
        } catch (NumberFormatException nfe) {
            return false;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableHospi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableHospi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE DE LA MASCOTA", "SEXO", "CEDULA DEL DUEÑO", "DUEÑO", "VETERINARIO", "FECHA DE INGRESO", "ESTADO"
            }
        ));
        jScrollPane1.setViewportView(jTableHospi);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 1260, 450));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Número de Cédula:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, -1, 30));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 80, 310, 30));

        jButton3.setText("Buscar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Finalizar Hospitalización");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 690, 190, 30));

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton2.setText("Ver hospitalización ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 690, 180, 30));

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setText("Atrás");
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 690, 190, 30));

        jLabel2.setFont(new java.awt.Font("Constantia", 1, 36)); // NOI18N
        jLabel2.setText("LISTA HOSPITALIZACIONES");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 660, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOP1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        if (esNumerico(jTextField1.getText()) == true) {
            int cont = 0;
            for (int i = 0; i < listPersonas.size(); i++) {
                if (listPersonas.get(i).getCedula().equals(jTextField1.getText())) {
                    cont++;
                }
            }
            if (cont != 0) {
                ArrayList<Hospitalizacion> listaCon;
                listaCon = ch.buscarConsulta(jTextField1.getText());
                llenarTabla(listaCon);
            } else {
                JOptionPane.showMessageDialog(null, "Persona no encontrada");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese solo numeros");
        }


    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (jTableHospi.getSelectedRow() >= 0) {
            DefaultTableModel table = (DefaultTableModel) jTableHospi.getModel();
            String nombreM = (String) table.getValueAt(jTableHospi.getSelectedRow(), 0);
            String cedula = (String) table.getValueAt(jTableHospi.getSelectedRow(), 2);
            for (int i = 0; i < listaHosp.size(); i++) {
                if (listaHosp.get(i).getMascota().getNombre().equals(nombreM)
                        && listaHosp.get(i).getMascota().getPersona().getCedula().equals(cedula)) {
                    table.setValueAt("Dado de Alta", jTableHospi.getSelectedRow(), 6);
                    listaHosp.get(i).setEstado("Dado de Alta");
                    JOptionPane.showMessageDialog(null, "Hospitalizacion Finalizada");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una fila");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel table = (DefaultTableModel) jTableHospi.getModel();
        String nombreM = (String) table.getValueAt(jTableHospi.getSelectedRow(), 0);
        String cedula = (String) table.getValueAt(jTableHospi.getSelectedRow(), 2);
        for (int i = 0; i < listaHosp.size(); i++) {
            if (listaHosp.get(i).getMascota().getNombre().equals(nombreM)
                    && listaHosp.get(i).getMascota().getPersona().getCedula().equals(cedula)) {
                eleccion = listaHosp.get(i);
            }
        }
        frmHospitalizacion fh = new frmHospitalizacion(new javax.swing.JFrame(), false, true, eleccion);
        fh.setVisible(true);

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmListaHospitalización.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmListaHospitalización.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmListaHospitalización.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmListaHospitalización.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmListaHospitalización dialog = new frmListaHospitalización(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableHospi;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
