/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.controladorMascota;
import Modelo.Mascota;
import Modelo.Persona;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Personal
 */
public class frmMascota extends javax.swing.JDialog {
    controladorMascota listaMascotas;
    /**
     * Creates new form frmMascota
     */
    public frmMascota(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //bloquearJtext();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMascotas = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextColorPelaje = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jTextNombreMascota = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jComboBoxSexo = new javax.swing.JComboBox<>();
        jButtonModificar = new javax.swing.JButton();
        jButtonRegistrar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jComboBoxTamaño = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Alertas = new javax.swing.JLabel();
        jTextRaza = new javax.swing.JTextField();
        jTextEdad = new javax.swing.JTextField();
        jTextEspecie = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jTextPresentarNombrePersona = new javax.swing.JTextField();
        jTextFieldPresentarApellidoPersona = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextBuscarCedula = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        AlertaBuscar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REGISTRAR MASCOTA");
        setAlwaysOnTop(true);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitulo.setText("REGISTRAR MASCOTA");
        getContentPane().add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 40, -1, -1));

        jTableMascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NOMBRE ", "ESPECIE", "RAZA", "SEXO", "CÉDULA", "DUEÑO"
            }
        ));
        jTableMascotas.setGridColor(new java.awt.Color(153, 153, 255));
        jScrollPane1.setViewportView(jTableMascotas);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 1090, 246));

        jPanel1.setOpaque(false);
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel23.setText("Raza:");
        jPanel1.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jTextColorPelaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextColorPelajeActionPerformed(evt);
            }
        });
        jPanel1.add(jTextColorPelaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, 155, 30));

        jLabel20.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel20.setText("Nombre:");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 57, -1, -1));

        jTextNombreMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreMascotaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextNombreMascota, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 270, 30));

        jLabel10.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel10.setText("Sexo: ");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 50, -1));

        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Macho", "Hembra" }));
        jPanel1.add(jComboBoxSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 90, 30));

        jButtonModificar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonModificar.setText("Modificar");
        jButtonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonModificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 90, 30));

        jButtonRegistrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonRegistrar.setText("Registrar");
        jButtonRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 100, 30));

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 90, 30));

        jLabel24.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel24.setText("Tamaño");
        jPanel1.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jComboBoxTamaño.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grande", "Mediano", "Pequeño" }));
        jPanel1.add(jComboBoxTamaño, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 100, 30));

        jLabel11.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel11.setText("Especie: ");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 60, 30));

        jLabel12.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel12.setText("Edad:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 87, -1));

        jLabel25.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        jLabel25.setText("Color de Pelaje :");
        jPanel1.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 120, -1, -1));

        Alertas.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        Alertas.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(Alertas, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 170, 290, 40));

        jTextRaza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextRazaActionPerformed(evt);
            }
        });
        jPanel1.add(jTextRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 155, 30));

        jTextEdad.setToolTipText("");
        jTextEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEdadActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEdad, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 155, 30));

        jTextEspecie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEspecieActionPerformed(evt);
            }
        });
        jPanel1.add(jTextEspecie, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 155, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 490, 1030, 220));

        jPanel6.setOpaque(false);
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Apellido");
        jPanel6.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 30, -1, 20));
        jPanel6.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 148, -1, -1));

        jTextPresentarNombrePersona.setEditable(false);
        jPanel6.add(jTextPresentarNombrePersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 180, 30));

        jTextFieldPresentarApellidoPersona.setEditable(false);
        jPanel6.add(jTextFieldPresentarApellidoPersona, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 170, 30));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Nombre");
        jPanel6.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 630, 80));

        jTextBuscarCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBuscarCedulaActionPerformed(evt);
            }
        });
        getContentPane().add(jTextBuscarCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 100, 310, 30));

        jButtonBuscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonBuscar.setText("Buscar");
        getContentPane().add(jButtonBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 100, -1, 30));

        AlertaBuscar.setFont(new java.awt.Font("Constantia", 1, 14)); // NOI18N
        AlertaBuscar.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(AlertaBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 100, 190, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Número de Cédula");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, 30));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FONDOP1.jpg"))); // NOI18N
        jLabelFondo.setText("jLabel2");
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextColorPelajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextColorPelajeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextColorPelajeActionPerformed

    private void jTextNombreMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreMascotaActionPerformed

    private void jButtonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonModificarActionPerformed

    private void jButtonRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarActionPerformed
        // TODO add your handling code here:
        if(listaMascotas==null){
            listaMascotas=new controladorMascota();
            listaMascotas.crearLista();
        }
        habititalJtext();        
        if(!jTextNombreMascota.getText().equals("")&&!jTextEspecie.getText().equals("")&&!jTextRaza.getText().equals("")
           &&!jTextEdad.getText().equals("")&&!jTextColorPelaje.getText().equals("")){
            if(esNumerico(jTextEdad.getText())){
                Persona p = new Persona(001, "PSN01", "CARLOS", "ORDOÑES", "GMAIL", "1150250921", "2572220", "MEXICO");
                int edad = Integer.parseInt(jTextEdad.getText());
                String nombreMascota = jTextNombreMascota.getText();
                listaMascotas.agregarMacota(001, "MT01",nombreMascota , edad, jTextRaza.getText(), jTextEspecie.getText(), jComboBoxTamaño.getSelectedItem().toString(), jComboBoxSexo.getSelectedItem().toString(), jTextColorPelaje.getText(), p);
                llenarTabla(listaMascotas.getListaMascota());
                limpiarJtext();
                Alertas.setText("");
            }else{
                jTextEdad.setText("");
                Alertas.setText("INGRESE LA EDAD EN NUMEROS");
            }
        }else{
            Alertas.setText("LLENE TODOS LOS CAMPOS");
        }
    }//GEN-LAST:event_jButtonRegistrarActionPerformed
    public void llenarTabla(ArrayList<Mascota> lista){
        DefaultTableModel modelo = new DefaultTableModel(new String[]{"NOMBRE","ESPECIE","RAZA","SEXO","CEDULA","DUEÑO"},lista.size());
        jTableMascotas.setModel(modelo);
        TableModel modeloDatos = jTableMascotas.getModel();
        for (int i = 0; i < lista.size(); i++) {
            Mascota mascota= lista.get(i);
            modeloDatos.setValueAt(mascota.getNombre(), i, 0);
            modeloDatos.setValueAt(mascota.getEspecie(), i, 1);
            modeloDatos.setValueAt(mascota.getRaza(), i, 2);
            modeloDatos.setValueAt(mascota.getSexo(), i, 3);
            modeloDatos.setValueAt(mascota.getPersona().getCedula(), i, 4);
            String dueño = mascota.getPersona().getNombre()+" "+mascota.getPersona().getApellido();
            modeloDatos.setValueAt(dueño, i, 5);
        }
    }
    
    private static boolean esNumerico(String cadena){
	try {
		Integer.parseInt(cadena);
		return true;
	} catch (NumberFormatException nfe){
		return false;
	}
    }
    public void limpiarJtext(){
        jTextNombreMascota.setText("");
        jTextColorPelaje.setText("");
        jTextEdad.setText("");
        jTextRaza.setText("");
        jTextEspecie.setText("");
        jTextBuscarCedula.setText("");
    }
    
    public void bloquearJtext(){
        jTextNombreMascota.disable();
        jComboBoxTamaño.disable();
        jTextColorPelaje.disable();
        jTextEdad.disable();
        jTextRaza.disable();
        jComboBoxSexo.disable();
        jTextEspecie.disable();
    }
    public void habititalJtext(){
        jTextNombreMascota.enable();
        jComboBoxTamaño.enable();
        jTextColorPelaje.enable();
        jTextEdad.enable();
        jTextRaza.enable();
        jComboBoxSexo.enable();
        jTextEspecie.enable();
    }
    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded

    }//GEN-LAST:event_jPanel1AncestorAdded

    private void jTextRazaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextRazaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextRazaActionPerformed

    private void jTextEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEdadActionPerformed

    private void jTextEspecieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEspecieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextEspecieActionPerformed

    private void jTextBuscarCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBuscarCedulaActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_jTextBuscarCedulaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMascota.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmMascota dialog = new frmMascota(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AlertaBuscar;
    private javax.swing.JLabel Alertas;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonModificar;
    private javax.swing.JButton jButtonRegistrar;
    private javax.swing.JComboBox<String> jComboBoxSexo;
    private javax.swing.JComboBox<String> jComboBoxTamaño;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableMascotas;
    private javax.swing.JTextField jTextBuscarCedula;
    private javax.swing.JTextField jTextColorPelaje;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextEspecie;
    private javax.swing.JTextField jTextFieldPresentarApellidoPersona;
    private javax.swing.JTextField jTextNombreMascota;
    private javax.swing.JTextField jTextPresentarNombrePersona;
    private javax.swing.JTextField jTextRaza;
    // End of variables declaration//GEN-END:variables
}
